### ISSUE TITLE
Need a host and port

### ISSUE THREAD

**Issue by lesliezhao** [zowe/zlux-server-framework#26]
In the log, an error message pops up, does this impact the zowe usage?
8-11-09 14:00:23.586 _unp.install WARNING¨ - Error: Proxy: need a host and port 
at Object.makeSimpleProxy (/home/zhaohl/zowe/0.9.2/zlux-proxy-server/js/proxy.js:58:11) 
at WebApp.makeExternalProxy (/home/zhaohl/zowe/0.9.2/zlux-proxy-server/js/we
at WebApp._installDataServices (/home/zhaohl/zowe/0.9.2/zlux-proxy-server/js
at next (native)                                                            
at WebApp.<anonymous> (/home/zhaohl/zowe/0.9.2/zlux-proxy-server/js/webapp.j
at next (native)                                                            
at tryCatcher (/home/zhaohl/zowe/0.9.2/zlux-proxy-server/js/node_modules/blu
at PromiseSpawn._promiseFulfilled (/home/zhaohl/zowe/0.9.2/zlux-proxy-server
at WebApp.installPlugin (/home/zhaohl/zowe/0.9.2/zlux-proxy-server/js/node_m
at PluginLoader.pluginLoader.on.event (/home/zhaohl/zowe/0.9.2/zlux-proxy-se
at emitOne (events.js:96:13)                                                
at PluginLoader.emit (events.js:188:7)                                      
at PluginLoader.loadPlugins (/home/zhaohl/zowe/0.9.2/zlux-proxy-server/js/pl
at Server.<anonymous> (/home/zhaohl/zowe/0.9.2/zlux-proxy-server/js/index.js
at next (native)                                                            
at tryCatcher (/home/zhaohl/zowe/0.9.2/zlux-proxy-server/js/node_modules/blu

**Comment by 1000TurquoisePogs** [comment]
It means that a proxy is not configured. This ticket should make the logging easier to identify how to fix: https://github.com/zowe/zlux-proxy-server/pull/33
But, if I understand it correctly, this proxy is for either the explorer or zosmf, so it wont break the Desktop but may break explorer apps or zlux-workflow until the proxy is configured.
