### ISSUE TITLE
Servers terminate after uncaught websocket errors running AppScan

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zlux-server-framework#88]
Security testers used AppScan Standard to send URLs to Zowe.  Some test runs caused certain Zowe STCs to terminate.  The terminated STCs are
```
ZOWESVR1 /bin/sh /opt/zowe/zowe-1.1.0/scripts/int
ZOWESVR3 /bin/sh ./nodeServer.sh --allowInvalidTL
ZOWESVR7 node --harmony zluxServer.js --config=..
ZOWESVR8 tee /opt/zowe/zowe-1.1.0/zlux-app-server
```
The errors in the ZOWESVR log are
case 1:
```
2019-04-09 18:35:39.082 _zsf.bootstrap WARNING¨ - Uncaught exception found. Error:
RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.startLoop (/opt/zowe/zowe-1.1.0/zlux-server-framework/node_modules/ws/lib/receiver.js:121:22)
    at Receiver._write (/opt/zowe/zowe-1.1.0/zlux-server-framework/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at Receiver.Writable.write (_stream_writable.js:245:11)
    at TLSSocket.socketOnData (/opt/zowe/zowe-1.1.0/zlux-server-framework/node_modules/ws/lib/websocket.js:795:35)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSWrap.onread (net.js:559:20)
Ý2019-04-09 18:35:39.082 _zsf.bootstrap WARNING¨ - Ending server process due to uncaught exception.
Ý2019-04-09 18:35:39.082 _zsf.bootstrap INFO¨ - Server shutting down, received signal=SIGQUIT
Ý2019-04-09 18:35:39.083 _zsf.network INFO¨ - (HTTPS) Closing server 0.0.0.0:8544
```
case 2:
```
[2019-04-11 14:21:02.037 _zsf.bootstrap WARNING] - Uncaught exception found. Error:                                                                             
TypeError: value.charAt is not a function                                                                                                                       
    at percentEncode (/opt/zowe/zowe-1.1.0/zlux-server-framework/plugins/config/lib/configService.js:113:19)                                                    
    at handleGet (/opt/zowe/zowe-1.1.0/zlux-server-framework/plugins/config/lib/configService.js:2430:41)                                                       
    at dispatchByMethod (/opt/zowe/zowe-1.1.0/zlux-server-framework/plugins/config/lib/configService.js:2346:14)                                                
    at determineResource (/opt/zowe/zowe-1.1.0/zlux-server-framework/plugins/config/lib/configService.js:2407:7)                                                
    at createMissingFoldersAsync (/opt/zowe/zowe-1.1.0/zlux-server-framework/plugins/config/lib/configService.js:2419:9)                                        
    at createMissingFolderAsync (/opt/zowe/zowe-1.1.0/zlux-server-framework/plugins/config/lib/configService.js:530:9)                                          
    at fs.mkdir (/opt/zowe/zowe-1.1.0/zlux-server-framework/plugins/config/lib/configService.js:407:5)                                                          
[2019-04-11 14:21:02.037 _zsf.bootstrap WARNING] - Ending server process due to uncaught exception.                                                             
[2019-04-11 14:21:02.037 _zsf.bootstrap INFO] - Server shutting down, received signal=SIGQUIT                                                                   
[2019-04-11 14:21:02.038 _zsf.network INFO] - (HTTPS) Closing server 0.0.0.0:8544
```

**Comment by John-A-Davies** [comment]
@1000TurquoisePogs Can you comment, please?

**Comment by John-A-Davies** [comment]
This was originally raised here https://github.ibm.com/Zowe-Commercial/zowe-core/issues/40 against Zowe v1.1.0.  
A very similar error to case 1 above is described here https://github.com/websockets/ws/issues/1140.  

What I think is happening ... AppScan sends a bunch of HTTP requests before it starts sending the URLs in the test script. In some cases this may cause a websocket error. Websocket is not part of Zowe, it is a service that Zowe calls. The problem is, Zowe code does not catch the websocket error, so the Zowe servers abend.

**Comment by 1000TurquoisePogs** [comment]
This will prevent server crashes, so that we can fix individual errors as they appear: https://github.com/zowe/zowe-install-packaging/pull/356

**Comment by John-A-Davies** [comment]
Got this message today 
```
[94] [2019-04-23 13:09:21.432 _zsf.bootstrap WARNING] - Uncaught exception found. Error:                                  
[94] RangeError: Invalid WebSocket frame: RSV1 must be clear                                                              
[94]     at Receiver.startLoop (/opt/zowe/zowe-1.1.0/zlux-server-framework/node_modules/ws/lib/receiver.js:121:22)        
[94]     at Receiver._write (/opt/zowe/zowe-1.1.0/zlux-server-framework/node_modules/ws/lib/receiver.js:69:10)            
[94]     at doWrite (_stream_writable.js:333:12)                                                                          
[94]     at writeOrBuffer (_stream_writable.js:319:5)                                                                     
[94]     at Receiver.Writable.write (_stream_writable.js:245:11)                                                          
[94]     at TLSSocket.socketOnData (/opt/zowe/zowe-1.1.0/zlux-server-framework/node_modules/ws/lib/websocket.js:795:35)   
[94]     at emitOne (events.js:96:13)                                                                                     
[94]     at TLSSocket.emit (events.js:188:7)                                                                              
[94]     at readableAddChunk (_stream_readable.js:176:18)                                                                 
[94]     at TLSWrap.onread (net.js:559:20)                                                                                
[94] [2019-04-23 13:09:21.432 _zsf.bootstrap WARNING] - Ending server process due to uncaught exception.                  
[94] [2019-04-23 13:09:21.433 _zsf.bootstrap INFO] - Server shutting down, received signal=SIGQUIT                        
[94] [2019-04-23 13:09:21.434 _zsf.network INFO] - (HTTPS) Closing server 0.0.0.0:8544                                    
restart worker 0                                                                                                          
Fork worker 0                                                                                                             
[16777310] Worker 0 pid 16777310                                                                                          
```
running `nodeCluster.sh`.

**Comment by John-A-Davies** [comment]
The calling sequence seems to be
```
run-zowe.sh -->  nodeCluster.sh --> zluxCluster.js --> node
``` 
and it's the `node` processes at the end of this chain that stop and restart during the test.  Counting the total processes at the start and end of the test, three processes were deleted and two were created.

**Comment by John-A-Davies** [comment]
Comment from @yanli : `@John Davies It seems Zowe server is pretty well now, I can’t break it so far…`
This is using `nodeCluster` instead of `nodeServer`.

**Comment by kathysychan** [comment]
I agree that if the AppScan test passes, the issue is much less severe. I think whether the issue should be closed depends on whether developer feels that the current way the uncaught exception is handled is how they want it to be. Is it currently simply just tolerating the traffic flow and restarting the server if it goes down? May be the server should properly log what’s exactly it’s tripped over so that the user can find out later on if they want. If the server should properly handle this kinds of traffic, another issue should be created to address it.

**Comment by John-A-Davies** [comment]
@1000TurquoisePogs The tester is re-running the AppScan test.  Thee ZOWESVR log is seeing
`RangeError: Invalid WebSocket frame: RSV1 must be clear` messages as before, but this time the number of STCs is staying at 18, not dropping to 17 as it did before.

In order to rewrite my verify script, I need to know what to expect after an AppScan run.  What do you suggest?

**Comment by 1000TurquoisePogs** [comment]
Thanks John. Do you know which query caused the org.zowe.configjs plugin to break its uri encoder (case 2)? #96 may fix, or may just be an extra check.

**Comment by 1000TurquoisePogs** [comment]
As you saw, if the server encounters something that would cause a crash, what instead happens is that the child process dies. The cluster parent process tries to maintain a number of child processes based on cpu activity, cpu count, and env vars on max or min process desired, so if it detects the number goes below threshold it will focus on making another child process. This doesn't take long, but it may cause a short period of unresponsiveness for some clients.

**Comment by kathysychan** [comment]
@1000TurquoisePogs  Should we still try to fix the root cause of the problem since theoretically, a malicious user could keep hitting Zowe server with this problematic traffic and cause the child processes to go up and down continuously? This could still be similar to a DoS attack.

**Comment by John-A-Davies** [comment]
It's better for the servers not to crash at all than to recover, however quickly.  

As a customer, if I saw the uncaught exceptions, I would look at the servers and think that stop/start was an error and call Zowe support.

Can we catch the exception, or is it buried in some websocket service that we can't touch?

Also, it would be good to know if and how we can enable tracing of requests to see which AppScan request takes down the server.

**Comment by 1000TurquoisePogs** [comment]
Of course, fixes must be done whenever there is a crashing problem. PR merged (#96) should fix it now.

**Comment by 1000TurquoisePogs** [comment]
By the way, whenever a crash happens, a stack is seen, so it does help! We have them in the logs here. Aside from that, the logger _zsf.routing https://github.com/zowe/zlux/wiki/Core-Loggers-for-zLUX should give more info.

**Comment by 1000TurquoisePogs** [comment]
I believe this has been fixed (for now). But, it is always important to re-evaluate how apps catch errors successfully, until a point at which we can better protect against plugins not catching errors.
